services:
  database:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:Coquelicot2}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:Tulipe5}
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"

volumes:
  database_data: